### ISSUE TITLE
learnr 0.9.1 release checklist

### ISSUE THREAD

**Issue by bborgesr** [rstudio/learnr#131]
## Code completion
- [x] Merge #130 

## Testing
- [x] Run the examples in the [examples directory](https://github.com/rstudio/learnr/tree/master/examples/) under Pandoc 1.9 and 2.0. Note if there is any difference visually. Note if there is any difference in the text diff.

## Release checklist (new PR, no code changes there)
- [x] Create a new branch for the release, like `v0.9.1`
- [x] Run `devtoools::check()` and address any possible problems
- [x] Bump version to `0.9.1` in NEWS and DESCRIPTION
- [x] Commit and push to github
- [x] Download “clean” copy of package and build source package
- [x] Upload to CRAN
- [x] When accepted to CRAN:
  - [x] create an annotated tag for the "version bump” commit
   ```sh
   git tag -a v0.9.1 -m "learnr 0.9.1 on CRAN"
   git push --tags
   ```
