### ISSUE TITLE
learnr 0.9.2 CRAN release checklist

### ISSUE THREAD

**Issue by bborgesr** [rstudio/learnr#147]
## Code completion
- [x] Merge #146 

## Testing
- [x] Run the examples in the [examples directory](https://github.com/rstudio/learnr/tree/master/examples/).

## Release checklist
- [x] Download “clean” copy of package and build source package
- [x] Make sure it passes r-hub checks: https://builder.r-hub.io
- [x] Upload to CRAN
- [x] When accepted to CRAN:
  - [x] create an annotated tag for the latest commit
   ```sh
   git tag -a v0.9.2 -m "learnr 0.9.2 on CRAN"
   git push --tags
   ```
